<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Ganesh" failures="1" tests="4" name="Personal Loan" time="0.066" errors="0" timestamp="2024-05-06T11:02:47 IST">
  <testcase classname="test.Test1" name="WebPersonalLoan" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Test1.WebPersonalLoan(Test1.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- WebPersonalLoan -->
  <testcase classname="test.Test2" name="APIPropertyLoan" time="0.001"/>
  <testcase classname="test.Test2" name="MobilePropertyLoan" time="0.001"/>
  <testcase classname="test.Test2" name="WebPropertyLoan" time="0.001"/>
  <testcase classname="test.Test1" name="MobilePersonalLoan" time="0.0">
    <ignored/>
  </testcase> <!-- MobilePersonalLoan -->
  <testcase classname="test.Test1" name="APIPersonalLoan" time="0.0">
    <ignored/>
  </testcase> <!-- APIPersonalLoan -->
</testsuite> <!-- Personal Loan -->
